config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "home#index"

  resources :entities
  resources :sales
  resources :payments
  resources :purchases

end

app/models/entity.rb
class Entity < ApplicationRecord

  has_many :sales
  has_many :payments

  validates_presence_of  :name
  validates_length_of :name,    :within => 5..50
  # validates_length_of :mobile,    :is => 10, :allow_blank => true
  # validates_format_of :mobile, :with => /\A[0-9]+\Z/, :message => " : Please enter correct mobile No", :allow_blank => true

  def get_entity_name_for_select_options
    "#{self.get_display_name} (#{mobile})"
  end

  def get_display_name
    self.company_name.present? ? self.company_name : self.name
  end
  
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController

  def index
    @entities = Entity.order('id desc').paginate(page: current_page, per_page: per_page)
  end

  def new
    @entity = Entity.new
  end

  def create
    @entity = Entity.new(entity_params)
    if @entity.save
      flash[:notice] = 'entity successfully created.'
      redirect_to entities_path
    else
      flash[:error] = @entity.errors.full_messages.first
      render :new
    end
  end

  def edit
    @entity = Entity.find_by_id(params[:id])
  end

  def update
   @entity = Entity.find_by_id(params[:id])
    if @entity.update_attributes(entity_params)
      flash[:notice] = 'entity successfully updated.'
      redirect_to entities_path
    else
      flash[:error] = @entity.errors.full_messages.first
      render :edit
    end
  end

  private
    def entity_params
      params.require(:entity).permit(:name, :mobile, :address, :company_name)
    end

end

app/views/entities/_form.html.erb
<form>
  <div class="form-group">
    <label class="padt10">Name</label>
    <%= f.text_field :name, :required => true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label class="padt10">Mobile Number</label>
    <%= f.text_field :mobile, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label class="padt10">Address</label>
    <%= f.text_area :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label class="padt10">Company Name</label>
    <%= f.text_field :company_name, class: 'form-control' %>
  </div>
  <%= f.submit "Save", :class => "btn btn-success" %>
  <%= link_to entities_path do %>
    <button type="button" class="btn btn-danger">Cancel</button>
  <% end %>
</form>

app/views/entities/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 primary">
      <div class="pad10 white--text font15">Edit Entity</div>
    </div>
  </div>

  <section>
    <%= form_for @entity do |f| %>
      <%= render "entities/form", :f => f %>
    <% end %>
  </section>
  
</div>

app/views/entities/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 primary">
      <div class="pad10 white--text font15">Entities</div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 text-left pad10">
      <%= link_to 'Home', root_path %> > Entities
    </div>
    <div class="col-md-6 text-right">
      <%= link_to new_entity_path do %>
        <button class="btn btn-success mar10" type="submit">Add New</button>
      <% end %>
    </div>
  </div>

  <table class="table">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th></th>
    </tr>

    <% @entities && @entities.each do |e| %>
      <tr>
        <td><%= e.id %></td>
        <td>
          <b><span class="font12"><%= e.company_name %></span></b>
          <br>
          mobile: <%= e.mobile %>
          <br>
          Address: <%= e.address %>
          <br>
          Name: <%= e.name %>
        </td>
        <td>
          <%= link_to edit_entity_path(e) do %>
            <button class="btn btn-info" type="submit">Edit</button>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>

</div>

app/views/entities/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 primary">
      <div class="pad10 white--text font15">Add New Entity</div>
    </div>
  </div>

  <section>
    <%= form_for @entity do |f| %>
      <%= render "entities/form", :f => f %>
    <% end %>
  </section>
  
</div>