config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "home#index"

  resources :entities
  resources :sales
  resources :payments
  resources :purchases

end

app/models/payment.rb
class Payment < ApplicationRecord
  enum payment_type: {cash_payment: 1, cheque_payment: 2, angadia_payment: 3}
  enum amount_type: {rupees: 1, dollar: 2}
  enum state: {active: 1, deleted: 2}

  belongs_to :entity
  belongs_to :paymentable, polymorphic: true

  validates_presence_of :entity_id, :amount

  after_save :update_sale_or_purchase

  def update_sale_or_purchase
    parent = self.paymentable
    all_payment_sum = parent.payments.active.sum(:amount)
    if parent.class == Sale
      parent.update_columns(total_received: all_payment_sum)
    else
      parent.update_columns(total_paid: all_payment_sum)
    end
  end

  def get_payment_type
    if self.cash_payment?
      'CASH'
    elsif self.cheque_payment?
      'CHEQUE'
    else
      'ANGADIA'
    end
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :find_parent, only: [:new, :create, :edit, :update]

  def new
    @payment = Payment.new
    @payments = @parent.payments.active.order('payment_date')
  end

  def create
    @payment = @parent.payments.new(payment_params)
    @payment.entity_id = @parent.entity_id
    if @payment.save
      flash[:notice] = 'payment successfully created.'
      redirect_to (@parent.class == Sale ?  sales_path : purchases_path)
    else
      flash[:error] = @payment.errors.full_messages.first
      render :new
    end
  end

  def edit
    @payment = Payment.find_by_id(params[:id])
  end

  def update
    @payment = Payment.find_by_id(params[:id])
    if @payment.update_attributes(payment_params)
      flash[:notice] = 'payment successfully updated.'
      redirect_to (@payment.paymentable_type == 'Sale' ? sales_path : purchases_path)
    else
      flash[:error] = @payment.errors.full_messages.first
      render :edit
    end
  end

  def destroy
    @payment = Payment.find_by_id(params[:id])
    if @payment.update_attributes(state: 2)
      flash[:notice] = 'payment successfully deleted.'
    else
      flash[:notice] = 'error on payment delete.'
    end
    redirect_to (@payment.paymentable_type == 'Sale' ? sales_path : purchases_path)
  end

  private
    def payment_params
      params.require(:payment).permit(:amount, :description, :from_person, :to_person,  :payment_type, :payment_date, :amount_type, :conversion_rate)
    end

    def find_parent
      if params[:sale_id].present?
        @parent = @sale = Sale.find_by_id(params[:sale_id])
      else params[:purchase_id].present?
        @parent = @purchase = Purchase.find_by_id(params[:purchase_id])
      end
    end

end

app/views/payments/_form.html.erb
<form>
  <div class="form-group">
    <% if @sale.present? %>
      <label class="padt10">Party: <%= @sale.entity.name %></label>
      <%= hidden_field_tag :sale_id, @sale.id %>
    <% elsif @purchase.present? %>
      <label class="padt10">Party: <%= @purchase.entity.name %></label>
      <%= hidden_field_tag :purchase_id, @purchase.id %>
    <% end %>
  </div>
  <div class="form-group">
    <label class="padt10">Amount Type</label>
    <%= select("payment", "amount_type", [['Rupees', 'rupees'],['Dollar', 'dollar']], {}, { :class => ""})%>
  </div>
  <div class="form-group">
    <label class="padt10">Amount</label>
    <%= f.text_field :amount, :required => true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="padt10">Conversion Rate</label>
    <%= f.text_field :conversion_rate, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="padt10">Description</label>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="padt10">Payment Type</label>
    <%= select("payment", "payment_type", [['Cash Payment', 'cash_payment'],['Cheque Payment', 'cheque_payment'],['Angadia Payment', 'angadia_payment']], {}, { :class => ""})%>
  </div>
  <div id="angadia_payment_options" style="display: none;">
    <div class="form-group">
      <label class="padt10">From person</label>
      <%= f.text_field :from_person, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label class="padt10">To person</label>
      <%= f.text_field :to_person, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label class="padt10">Payment Date</label>
    <%= f.date_select :payment_date, order: [:day, :month, :year] %>
  </div>
  <%= f.submit "Save", :class => "btn btn-success" %>
  <%= link_to payments_path do %>
    <button type="button" class="btn btn-danger">Cancel</button>
  <% end %>
</form>


<script type="text/javascript">
  $('#payment_payment_type').on('change', function() {
    if( this.value == 'angadia_payment'){
      $('#angadia_payment_options').show()
    }else{
      $('#angadia_payment_options').hide()
    }
  });
</script>

app/views/payments/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 primary">
      <div class="pad10 white--text font15">Edit Payment</div>
    </div>
  </div>

  <section>
    <%= form_for @payment do |f| %>
      <%= render "payments/form", :f => f %>
    <% end %>
  </section>
  
</div>

app/views/payments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 primary">
      <div class="pad10 white--text font15">Payments</div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 text-left pad10">
      <%= link_to 'Home', root_path %> > Payments
    </div>
    <div class="col-md-12 text-right">
      <%= link_to new_payment_path do %>
        <button class="btn btn-success mar10" type="submit">Add New</button>
      <% end %>
    </div>
  </div>
  <table class="table">
    <tr>
      <th>Date</th>
      <th>Party</th>
      <th>Amount</th>
      <th>Type</th>
      <th></th>
    </tr>
    <% @payments && @payments.each do |p| %>
      <tr>
        <td><%= p.payment_date.strftime("%d/%m/%y") %></td>
        <td>
          <b><span class="font12"><%= p.entity.name %></span></b>
        </td>
        <td>
          <% if p.rupees? %>
            &#8377; <%= number_with_delimiter(p.amount) %>
          <% else %>
            $ <%= number_with_delimiter(p.amount) %>(<%= p.conversion_rate %>)
          <% end %>
        </td>
        <td><%= p.payment_type %></td>
        <td>
          <%= link_to edit_payment_path(p) do %>
            <button class="btn btn-info" type="submit">Edit</button>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/payments/new.html.erb
<div class="container">
  <div class="padt50">
    All Payments
    <table class="table table-striped table-bordered">
      <tr>
        <th>Date</th>
        <th>Amount</th>
        <th>Type</th>
        <th>from_person</th>
        <th>to_person</th>
        <th>description</th>
        <th></th>
      </tr>
      <% @payments && @payments.each do |p| %>
        <tr>
          <td><%= p.payment_date.strftime("%d/%m/%y") %></td>
          <td>
            <% if p.rupees? %>
              &#8377; <%= number_with_delimiter(p.amount) %>
            <% else %>
              $ <%= number_with_delimiter(p.amount) %>(<%= p.conversion_rate %>)
            <% end %>
          </td>
          <td><%= p.get_payment_type %></td>
          <td><%= p.from_person %></td>
          <td><%= p.to_person %></td>
          <td><%= p.description %></td>
          <td>
            <%= link_to edit_payment_path(p) do %>
              <button class="btn btn-info" type="submit">Edit</button>
            <% end %>
            <%= link_to payment_path(p), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <button class="btn btn-danger" type="submit">Delete</button>
            <% end %>
          </td>
        </tr>
      <% end %>
      <tr>
        <th>Total</th>
        <th colspan="6">
          <%= "#{number_with_delimiter(get_conversion_rate(@payments)[:total])} (#{get_conversion_rate(@payments)[:rate]})" if @payments %>
        </th>
      </tr>
    </table>
  </div>

  <div class="row">
    <div class="col-md-12 primary">
      <div class="pad10 white--text font15">Add New Payment</div>
    </div>
  </div>
  <section>
    <%= form_for @payment do |f| %>
      <%= render "payments/form", :f => f %>
    <% end %>
  </section>
</div>