config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "home#index"

  resources :entities
  resources :sales
  resources :payments
  resources :purchases

end

app/models/sale.rb
class Sale < ApplicationRecord

  enum sale_type: {polish: 1, rough: 2}
  enum payment_type: {cash_payment: 1, cheque_payment: 2, angadia_payment: 3}
  enum amount_type: {rupees: 1, dollar: 2}
  enum state: {active: 1, deleted: 2}
  

  belongs_to :entity
  has_many :payments, as: :paymentable

  validates_presence_of :entity_id, :quantity, :amount, :payment_type

  def final_quantity
    self.quantity - self.return_quantity
  end

  def get_payment_type
    if self.cash_payment?
      'CASH'
    elsif self.cheque_payment?
      'CHEQUE'
    else
      'ANGADIA'
    end
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :find_sale, only: [:edit, :update, :destroy]

  def index
    if display_cheque?
      @sales = Sale.includes(:entity).active.cheque_payment.order('id desc').paginate(page: current_page, per_page: per_page)
    else
      @sales = Sale.includes(:entity).active.order('id desc').paginate(page: current_page, per_page: per_page)
    end
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(sale_params)
    if @sale.save
      flash[:notice] = 'sale successfully created.'
      redirect_to sales_path
    else
      flash[:error] = @sale.errors.full_messages.first
      render :new
    end
  end

  def edit
    @sale = Sale.find_by_id(params[:id])
  end

  def update
    @sale = Sale.find_by_id(params[:id])
    if @sale.update_attributes(sale_params)
      flash[:notice] = 'sale successfully updated.'
      redirect_to sales_path
    else
      flash[:error] = @sale.errors.full_messages.first
      render :edit
    end
  end

  def destroy
    if @sale.update_attributes(state: 2)
      flash[:notice] = 'sale successfully deleted.'
    else
      flash[:notice] = 'error on sale delete.'
    end
    redirect_to sales_path
  end

  private
    def find_sale
      @sale = Sale.find_by_id(params[:id])
      if @sale.blank?
        flash[:error] = 'invalid sale'
        redirect_to sales_path
      end
    end

    def sale_params
      params.require(:sale).permit(:entity_id, :sale_type, :description, :broker_name, :quantity, :return_quantity, :percent_output, :amount, :amount_type, :conversion_rate, :payment_type, :payment_date, :terms, :invoice_number)
    end

end

app/views/sales/_form.html.erb
<form>
  <div class="form-group">
    <label class="padt10">Party</label>
    <%= f.collection_select :entity_id, Entity.all.order('name') , :id, :get_entity_name_for_select_options, {}, { :class => ""} %>
  </div>
  <div class="form-group">
    <label class="padt10">Sale Type</label>
    <%= select("sale", "sale_type", [['Polish', 'polish'],['Rough', 'rough']], {}, { :class => ""})%>
  </div>
  <div class="form-group">
    <label class="padt10">Invoice Number</label>
    <%= f.text_field :invoice_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="padt10">Description</label>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="padt10">Broker Name</label>
    <%= f.text_field :broker_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="padt10">Quantity</label>
    <%= f.text_field :quantity, :required => true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="padt10">Return Quantity</label>
    <%= f.text_field :return_quantity, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="padt10">Amount Type</label>
    <%= select("sale", "amount_type", [['Rupees', 'rupees'],['Dollar', 'dollar']], {}, { :class => ""})%>
  </div>
  <div class="form-group">
    <label class="padt10">Amount</label>
    <%= f.text_field :amount, :required => true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="padt10">Conversion Rate</label>
    <%= f.text_field :conversion_rate, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label class="padt10">Payment Type</label>
    <%= select("sale", "payment_type", [['Cash Payment', 'cash_payment'],['Cheque Payment', 'cheque_payment'],['Angadia Payment', 'angadia_payment']], {}, { :class => ""})%>
  </div>
  <div class="form-group">
    <label class="padt10">Payment Date</label>
    <%= f.date_select :payment_date, order: [:day, :month, :year] %>
  </div>
  <div class="form-group">
    <label class="padt10">terms</label>
    <%= f.text_field :terms, class: 'form-control' %>
  </div>
  <%= f.submit "Save", :class => "btn btn-success" %>
  <%= link_to sales_path do %>
    <button type="button" class="btn btn-danger">Cancel</button>
  <% end %>
</form>

app/views/sales/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 primary">
      <div class="pad10 white--text font15">Edit Sale</div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 text-left pad10">
      <%= link_to 'Home', root_path %> > <%= link_to 'Sales', sales_path %> > Edit
    </div>
  </div>
  <section>
    <%= form_for @sale do |f| %>
      <%= render "sales/form", :f => f %>
    <% end %>
  </section>
</div>

app/views/sales/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 primary">
      <div class="pad10 white--text font15">Sales</div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 text-left pad10">
      <%= link_to 'Home', root_path %> > Sales
    </div>
    <div class="col-md-6 text-right">
      <%= link_to new_sale_path do %>
        <button class="btn btn-success mar10" type="submit">Add New</button>
      <% end %>
    </div>
  </div>

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Date</th>
        <th>Invoice</th>
        <th>Party</th>
        <th>Carat</th>
        <th>Amount</th>
        <th>Total</th>
        <th>Received</th>
        <th>Type</th>
        <th>Terms</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @sales && @sales.each do |s| %>
        <tr>
          <td><%= s.payment_date.strftime("%d/%m/%y") %></td>
          <td><%= s.invoice_number %></td>
          <td>
            <b><span class="font12"><%= s.entity && s.entity.get_display_name %></span></b>
          </td>
          <td><%= s.final_quantity %></td>
          <td>
            <% if s.rupees? %>
              &#8377;<%= number_with_delimiter(s.amount.to_i) %>
            <% else %>
              $<%= number_with_delimiter(s.amount.to_i) %> <br>(<%= s.conversion_rate %>)
            <% end %>
          </td>
          <td align="right">
            <% if s.rupees? %>
              <% total_amount = (s.amount * s.final_quantity).to_i %>
            <% else %>
              <% total_amount = (s.amount * s.final_quantity * s.conversion_rate).to_i %>
            <% end %>
            <% gst_amount = (s.cheque_payment? ? (total_amount*0.25/100).to_i : 0) %>
            &#8377;<%= number_with_delimiter(total_amount) %><br>
            <% if gst_amount > 0 %>
              <span class="font07">GST</span> + &#8377;<%= number_with_delimiter(gst_amount)%>
            <% end %>
            <hr style="margin-top: 0px; margin-bottom: 0px;">
            <span class="font07">Total</span> = &#8377;<%= number_with_delimiter(total_amount + gst_amount)%>
          </td>
          <td class="<%= total_amount <= s.total_received ? 'success' : 'danger' %>">          
            &#8377;<%= number_with_delimiter(s.total_received) %>
          </td>
          <td><%= s.get_payment_type %></td>
          <td><%= (s.payment_date + s.terms.days).strftime("%d/%m/%y") if s.terms.present? %></td>
          <td>
            <%= link_to edit_sale_path(s) do %>
              <button class="btn btn-info" type="submit">Edit</button>
            <% end %>
            <%= link_to sale_path(s), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <button class="btn btn-danger" type="submit">Delete</button>
          <% end %>
            <%= link_to new_payment_path(sale_id: s.id) do %>
              <button class="btn btn-info" type="submit">Payments</button>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/sales/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 primary">
      <div class="pad10 white--text font15">Add New Sale</div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 text-left pad10">
      <%= link_to 'Home', root_path %> > <%= link_to 'Sales', sales_path %> > New
    </div>
  </div>
  <section>
    <%= form_for @sale do |f| %>
      <%= render "sales/form", :f => f %>
    <% end %>
  </section>
</div>